### ISSUE TITLE
Private IP address for container group

### ISSUE THREAD

**Issue by clement128** [CompositionalIT/farmer#125]
Hi there, is me again :)

I tried to deploy a container group for testing, but it show me the error 
```
"IP Address type in container group 'MyContainerGroup' is invalid. Private IP address is only supported when network profile is defined
```

But how I can define it?

**Comment by isaacabraham** [comment]
Can you post a sample of the invalid farmer builder?

**Comment by clement128** [comment]
hi @isaacabraham 

here is the sample
```f#


let testContainer = 
    container {
        name "testing"
        image "microsoft/aci-helloworld"
        os_type ContainerGroupOsType.Linux
        restart_policy ContainerGroupRestartPolicy.Always
        group_name "testing"
        ip_address ContainerGroupIpAddressType.PrivateAddress [ TCP, 80us ]
    }

let deployment = 
    arm {
        location JapanEast
        add_resource testContainer
    }

deployment
|> Deploy.execute "ForTesting" []
|> printfn "%A"

```

if deploy from yaml I need to define 
```yaml
ipAddress:
        ip: 10.0.0.4
        ports:
            - port: 80
              protocol: TCP
        type: Private
    networkProfile:
        id: <MyNetworkProfileId>
```
